### ISSUE TITLE
"OSError: [Errno 18] Invalid cross-device link" with result.save_as command using Python

### ISSUE THREAD

**Issue by leophill** [AdobeDocs/pdfservices-api-documentation#147]
result.save_as command while using Python  raises "OSError: [Errno 18] Invalid cross-device link" error when the output file is saved on a different filesystem. This is linked to the use **os.rename** in the following python excerpt:

  44             if not os.path.exists(abs_path):
---> 45                 os.rename(self._file_path, abs_path)
     46                 return

This should be replaced with **shutil.move**, for example, as this works across filesystems.

**Comment by thedevhack** [comment]
I am trying to send data from Django and then calling the function of extracting pdf contents it runs successfully and gives me the transaction id but the file of zip is not getting saved in the location I provided in save_as() while saving the result but when I run the same code locally and not using Django then it stores the zip in /tmp folder of my Linux system

**Comment by thedevhack** [comment]
@leophill hey did you find out any solutions for the isssue you mentioned?

**Comment by cfjedimaster** [comment]
Hi, sorry, but this repository is only for the API Services documentation. Please report your issues to our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK.
