### ISSUE TITLE
Could you please explain what is contained in bounds output from extract_txt_from_pdf.py file

### ISSUE THREAD

**Issue by rishisriv** [AdobeDocs/pdfservices-api-documentation#152]
Issue in /src/pages/overview/pdf-extract-api/index.md

Here is an example
{
			"Bounds": [
				425.8959197998047,
				313.67999267578127,
				433.39520263671877,
				354.9148254394531
			],
			"Font": {
				"alt_family_name": "Helvetica",
				"embedded": true,
				"encoding": "WinAnsiEncoding",
				"family_name": "Helvetica",
				"font_type": "Type1",
				"italic": false,
				"monospaced": false,
				"name": "FDUVGA+Helvetica-Bold",
				"subset": true,
				"weight": 700
			},
			"HasClip": false,
			"Lang": "en",
			"Page": 0,
			"Path": "//Document/Sect/Table/TR[9]/TD[2]/P",
			"Rotation": 90.0,
			"Text": "$12,825.00 ",
			"TextSize": 8.003494262695313,
			"attributes": {
				"LineHeight": 9.625
			}
		},

**Comment by cfjedimaster** [comment]
Hi, for usage questions and the such, please use our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?filter=all&sort=latest_replies&tabid=discussions
