### ISSUE TITLE
Headers of tables not repeating with Power Automate

### ISSUE THREAD

**Issue by TWickert** [AdobeDocs/pdfservices-api-documentation#189]
### Expected Behaviour
When flagging the header of my table as repeatable row, I expect it to be repeated on each page 
![image](https://user-images.githubusercontent.com/10076825/178541964-70f14c3e-de87-4cf1-bc97-5792739fb389.png)

### Actual Behaviour
The Header is not repeating.
See Attached PDf file : 

### Reproduce Scenario (including but not limited to)
Just create a template in Word like the one attached.
Flag it as repeatable and use it to produce a PDF file With the JSON attached aswell

#### Platform and Version
Power Automate.

#### Sample Code that illustrates the problem.
See JSON containing the items to populate the word.
See File attached for the word template

JSON:
`{
  "DocSanitaire": [
    {
      "No Agrement": "FR 67 411 001 CE",
      "DésignationProduit": "Munster Bio 200g",
      "TraitementDuLait": "pasteurise",
      "TraitementDuLaitEN": "pasteurized",
      "Affinage": "14",
      "TypeLait": "Vache",
      "TypeLaitEN": "Cow",
      "TypeFromage": "Fromage pâte molle",
      "TypeFromageEN": "Soft ripened cheese",
      "PateCroute": "Lavee",
      "PateCrouteEN": "Washed",
      "MatiereGrasse": 50,
      "TEFD": "70.83",
      "PoidsNet": "2.400",
      "Colis": 1,
      "Producteur": "Siffert-Frech Affineurs",
      "AdresseProducteur": "35 rte de Rosenwiller 67560 Rosheim FRANCE"
    },
    {
      "No Agrement": "FR 25 462 005 CE",
      "DésignationProduit": "Prefere des Montagnes nøLotx6/OU",
      "TraitementDuLait": "pasteurise",
      "TraitementDuLaitEN": "pasteurized",
      "Affinage": "6",
      "TypeLait": "Vache",
      "TypeLaitEN": "Cow",
      "TypeFromage": "Fromage pâte molle",
      "TypeFromageEN": "Soft ripened cheese",
      "PateCroute": "Mixte",
      "PateCrouteEN": "Mixed",
      "MatiereGrasse": 45,
      "TEFD": "67.08",
      "PoidsNet": "3.000",
      "Colis": 1,
      "Producteur": "Fromagerie Badoz",
      "AdresseProducteur": "30 rue Arago 25300 PONTARLIER FRANCE"
    },
    {
      "No Agrement": "FR 52 465 001 CE",
      "DésignationProduit": "Langres Champenois Panier",
      "TraitementDuLait": "thermise",
      "TraitementDuLaitEN": "thermised",
      "Affinage": "60",
      "TypeLait": "Vache",
      "TypeLaitEN": "Cow",
      "TypeFromage": "Fromage pâte molle",
      "TypeFromageEN": "Soft ripened cheese",
      "PateCroute": "Lavee",
      "PateCrouteEN": "Washed",
      "MatiereGrasse": 50,
      "TEFD": "66.67",
      "PoidsNet": "8.640",
      "Colis": 6,
      "Producteur": "Fromagerie Schertenleib",
      "AdresseProducteur": "6 rue de la Laiterie 52140 SAULXURES FRANCE"
    },
    {
      "No Agrement": "FR 85 133 002 CE",
      "DésignationProduit": "Tomme Chevre Muscadet LRDC",
      "TraitementDuLait": "pasteurise",
      "TraitementDuLaitEN": "pasteurized",
      "Affinage": "120",
      "TypeLait": "Chevre",
      "TypeLaitEN": "Goat",
      "TypeFromage": "Fromage pâte pressée non cuite",
      "TypeFromageEN": "Semi-hard cheese",
      "PateCroute": "Lavee",
      "PateCrouteEN": "Washed",
      "MatiereGrasse": 50,
      "TEFD": "62.00",
      "PoidsNet": "13.500",
      "Colis": 3,
      "Producteur": "union laitiere venise verte",
      "AdresseProducteur": "la garenne 85420 MAILLEZAIS FRANCE"
    },
    {
      "No Agrement": "FR 36 233 001 CE",
      "DésignationProduit": "Pyramide Chevre XD berc 220g Lot",
      "TraitementDuLait": "pasteurise",
      "TraitementDuLaitEN": "pasteurized",
      "Affinage": "12",
      "TypeLait": "Chevre",
      "TypeLaitEN": "Goat",
      "TypeFromage": "Fromage pâte molle",
      "TypeFromageEN": "Soft ripened cheese",
      "PateCroute": "Cendree",
      "PateCrouteEN": "Ashed",
      "MatiereGrasse": 45,
      "TEFD": "70.67",
      "PoidsNet": "2.640",
      "Colis": 2,
      "Producteur": "SA Fromagerie Pierre Jacquin & Fils",
      "AdresseProducteur": "9 RTE de meusnes 36600 LA VERNELLE FRANCE"
    }
  ],
  "AllWeight": "30.18",
  "SommeConditionnnement": "13"
}`

Attached Files :
[DocSanitaire (5).pdf](https://github.com/AdobeDocs/pdfservices-api-documentation/files/9095004/DocSanitaire.5.pdf)
[SanitaryDocumentTemplate.docx](https://github.com/AdobeDocs/pdfservices-api-documentation/files/9095014/SanitaryDocumentTemplate.docx)

**Comment by cfjedimaster** [comment]
Hi, this repository is for PDF Services *documentation*. Please report your issue on our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions&topics=label-documentgenerationapi
