### ISSUE TITLE
Please provide sample code to convert excel to PDF

### ISSUE THREAD

**Issue by vkumarrl** [AdobeDocs/pdfservices-api-documentation#194]
Issue in /src/pages/overview/pdf-services-api/howtos/create-pdf.md

**Comment by cfjedimaster** [comment]
This repo is not for technical support, and while technically you are asking for a change to the docs, this is really more appropriate for our support forums: https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all
