### ISSUE TITLE
unable to view pdf using iOS 15.7

### ISSUE THREAD

**Issue by praveeninrace** [AdobeDocs/pdfservices-api-documentation#266]
Issue in /src/pages/overview/pdf-embed-api/index.md

We are getting an exception while using pdf-embed-api and it does not work on few iOS versions. Please advise.

**Comment by cfjedimaster** [comment]
This repository is not for technical support. Please post your question to our forums: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions&topics=label-documentgenerationapi
