### ISSUE TITLE
Support/Unsupported fonts?

### ISSUE THREAD

**Issue by gregstackaero** [AdobeDocs/pdfservices-api-documentation#296]
Issue in /src/pages/overview/document-generation-api/stylingformattingtags.md

I tried reviewing the above link to find out what fonts are supported, but can't see any references in the documentation. We are trying to use 2 fonts in our Word templates that are returning different fonts when the PDF is returned via the API. These fonts are:

- Helvetica Neue
- Montserrat

Is there a list of supported fonts somewhere?

**Comment by cfjedimaster** [comment]
I believe what you want is here, https://developer.adobe.com/document-services/docs/overview/pdf-services-api/howtos/create-pdf/#create-a-pdf, in the note:

 If a Microsoft Word/PowerPoint input file has an embedded TrueType font, the output pdf will also contain the same embedded TrueType font. For more information, refer [Benefits of embedding custom fonts](https://support.microsoft.com/en-us/office/benefits-of-embedding-custom-fonts-cb3982aa-ea76-4323-b008-86670f222dbc#OfficeVersion=Windows).

**Comment by gregstackaero** [comment]
Perfect. Thank you.

**Comment by gregstackaero** [comment]
We tried this, however we weren't successful - could it be the way we are sending the template for processing? 

We don't have the template saved on our servers, but rather we handle it as a Base64 encoded document within the .NET SDK. I'm guessing the embedded fonts could be lost as part of the conversion to Base64 before we call DocumentMergeOperation.CreateNew(options);

**Comment by gregstackaero** [comment]
Pls disregard. We got this to work via Adobe word plugin which merges the JSON content without touching our code. The difference is that embedded fonts take up a large amount of file space (template becomes 5MB+) so we will likely limit ourselves to standard fonts
