### ISSUE TITLE
Cannot move text comment when enableAnnotationAPIs is true.

### ISSUE THREAD

**Issue by YMistake** [AdobeDocs/pdfservices-api-documentation#303]
If I enabled enableAnnotationAPIs then add text comment into pdf file. When I move that text comment box, it will be disappear and got an error in console "Cannot read properties of undefined (reading 'color')"

<img width="410" alt="image" src="https://user-images.githubusercontent.com/21216075/203222539-e770b303-0e9d-489c-adb6-23cfafa2b3b8.png">

**Comment by cfjedimaster** [comment]
Hi, as stated when you filed a new issue, this repo is not for technical support, but for the technical documentation. Please file your issue here: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?filter=all&sort=latest_replies&tabid=discussions
