### ISSUE TITLE
PDF Embed API Doesn't Work

### ISSUE THREAD

**Issue by robertjp** [AdobeDocs/pdfservices-api-documentation#304]
PDF Embed API Doesn't Work Period!

I've followed the instructions down to a "T", it will work several times and give a "File preview not available" error.

This situation exists in both local and remote environments. Domain settings are as Adobe instructions state.

As I stated above the code will sometimes (rarely) work for a day sometimes longer, and it just stops working.

I'm in the Asia Pacific region, I don't know if that's a factor.

Also, with a new client id, it will work once or twice.

**Comment by cfjedimaster** [comment]
Hi, as stated when you filed this issue, this repository is for the documentation only, and support questions should be posted here, https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK?filter=all&sort=latest_replies&tabid=discussions.

That being said, when you do post, you need to provide more detail. Saying it doesn't work doesn't actually describe how it fails. Do you see any error messages? Do you see anything? Also, if you have an example online where we can see, it will help us a lot.
