### ISSUE TITLE
  embedded modern PDF viewer is not working Properly 

### ISSUE THREAD

**Issue by ritikmaheshwari1203** [AdobeDocs/pdfservices-api-documentation#408]
Issue in /src/pages/overview/pdf-embed-api/modernviewer.md

   when a user try to access any PDF from our Website then the PDF  is loading very slowly and we are facing thsi issue from two days and my code is given below

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>ReadnWatch</title>
</head>
<body style="margin: 0px">
    <div id="adobe-dc-view"></div>
    
</body>

<script src="https://documentservices.adobe.com/view-sdk/viewer.js"></script>
<script type="text/javascript">
function ShowPDF(){
    comsole.log("hello")
}

    let params = new URLSearchParams(location.search);
let url2= params.get('location') ;
let name=params.get('pdfname') ;
	document.addEventListener("adobe_dc_view_sdk.ready", function(){ 
		var adobeDCView = new AdobeDC.View({clientId: "39ae75d0aae14c3384700647a85ed1d7", divId: "adobe-dc-view"});
		adobeDCView.previewFile({
			content:{location: {url: url2}},
			metaData:{fileName: name}
		}, {showDownloadPDF: false, showPrintPDF: false});
	});

/*
Copyright 2019 Adobe
All Rights Reserved.

NOTICE: Adobe permits you to use, modify, and distribute this file in
accordance with the terms of the Adobe license agreement accompanying
it. If you have received this file from a source other than Adobe,
then your use, modification, or distribution of it requires the prior
written permission of Adobe.
*/

/* Control the default view mode */

</script>
</html>`

**Comment by cfjedimaster** [comment]
Hi, this repo is for documentation source. For support, please post to our forums here: https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all
