### ISSUE TITLE
Rendering of PDF is slow

### ISSUE THREAD

**Issue by ChristoReeganRajV** [AdobeDocs/pdfservices-api-documentation#415]
Issue in /src/pages/overview/pdf-embed-api/index.md

We have been using embed API for filling the pdf forms. While loading the PDF Form on an android device its taking longer time

**Comment by cfjedimaster** [comment]
This repository is for documentation and documentation issues. For general support, please use the forum: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?filter=all&sort=latest_replies&tabid=discussions
