### ISSUE TITLE
Trial account in PDF Adobe API to payment

### ISSUE THREAD

**Issue by jmturon62** [AdobeDocs/pdfservices-api-documentation#437]
Hi,

I've an AWS account: and when I go to the list of suscriptions, I can see the suscription to Adobe PDF Services API.

I go to "Product Configuration" - "Set up your account" - jumps to Adobe Developer, and then --> "Manage in developer console": Appears the credentials and a project called: “Project PDF Gratuito”.

I want to change this project, that is a trial account with 1000 transactions, for a suscription account (payment by use, without limits), but if I try to use the option of "Create new credentials", it says that "You already have a credential".

How can I create these new credentials for a suscription account?

Thanks

**Comment by cfjedimaster** [comment]
This repository is for the documentation files, not support. Please post your question on our forums: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?filter=all&sort=latest_replies&tabid=discussions
