### ISSUE TITLE
Is PDF Extract API doing virus and vulnerability check? 

### ISSUE THREAD

**Issue by pankajv82** [AdobeDocs/pdfservices-api-documentation#438]
We are client of "PDF Extract API", we wanted to check if Adobe is doing any kind of  virus and vulnerability check on the PDF files?

**Comment by cfjedimaster** [comment]
This repository is for documentation and not general support. Please post your question here: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions

**Comment by pankajv82** [comment]
Ok, posted there. Thanks for quick reply.
