### ISSUE TITLE
A nested table with merge data results in the outer table being looped over, not the inner one.

### ISSUE THREAD

**Issue by djcard** [AdobeDocs/pdfservices-api-documentation#442]
Issue in /src/pages/overview/document-generation-api/templatetags.md
The issue isn't the docs but with the actual service. A common scenario is to use a table to help the layout in complex Word documents. When a dynamic table is inserted inside another table, the outer table is looped over with one row of data being put into each instance of the inner table. More simply: A 1 page nested table with 10 rows turns into 10 pages with one row on each page. 

[NestedTableExample.docx](https://github.com/AdobeDocs/pdfservices-api-documentation/files/10962829/NestedTableExample.docx)
[NestedTableData.txt](https://github.com/AdobeDocs/pdfservices-api-documentation/files/10962852/NestedTableData.txt)

**Comment by cfjedimaster** [comment]
As stated in the issue template, please post technical support issues here: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions

**Comment by cfjedimaster** [comment]
I was a bit salty in my response - I'm sorry and thank you for letting me know the link from the live docs bypasses the notice!

**Comment by djcard** [comment]
All good.  I was probably a little self righteous when I responded. You are the man, Obi Wan. Thanks for doing what you do! 😊

 

Dan Card
