### ISSUE TITLE
Crash on iPhone on zoom

### ISSUE THREAD

**Issue by skcuslleb** [AdobeDocs/pdfservices-api-documentation#452]
I'm using the SDK to display a pdf on a page using the IN_LINE embed mode. Everything works ok until I pinch to zoom on iPhone (Safari and Chrome) at which point the page crashes. I've tried hooking into the developer console, but I don't get any perceptible changes before the crash.

1. Go to http://staugustinesvancouver.com/solids on an iPhone
2. Pinch to zoom
3. Observe crash

- no crash, just zoom

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.3.1
 - Browser: Safari

Here's how the document load is triggered initially
```html
<script type="text/javascript">
	document.addEventListener("adobe_dc_view_sdk.ready", function(){
	  switchDocument($('#dinnerMenu'));
	});
</script>
```

And the relevant Embed API code
```javascript
function switchDocument(parentDiv){
  var adobeDCView = new AdobeDC.View({clientId: <ID>, divId: 'dinnerMenu'});
  adobeDCView.previewFile({
    content:{location: {url: parentDiv.data('pdf-path')}},
    metaData:{fileName: parentDiv.data('pdf-filename')}
  }, 
	{ 
		embedMode: "IN_LINE", defaultViewMode: "FIT_PAGE"
	});
};
```

**Comment by cfjedimaster** [comment]
Hi, this repo is for documentation. Please report support issues here: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?filter=all&sort=latest_replies&tabid=discussions
