### ISSUE TITLE
Permission.EDIT_DOCUMENT_ASSEMBLY not working

### ISSUE THREAD

**Issue by bbpcoforge** [AdobeDocs/pdfservices-api-documentation#460]
Issue in /src/pages/overview/pdf-services-api/howtos/protect-pdf.md

Hi,

I was evaluating pdfservices and edit_document_assembly in particular from https://github.com/adobe/pdfservices-java-sdk-samples.

In ProtectPDFWithOwnerPassword.java , EDIT_DOCUMENT_ASSEMBLY is set but still is shown as "Not Allowed" in adobe reader.

Thanks

**Comment by adityaganotra** [comment]
Hi, this repo is for documentation. Please report support issues here: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions&topics=label-pdfservicesapi
