### ISSUE TITLE
Broken link to white paper

### ISSUE THREAD

**Issue by AdeelK93** [AdobeDocs/pdfservices-api-documentation#471]
## READ ME FIRST
This repository is for documentation related to Adobe's PDF Services. If you have a support question, please ask it on our forums: https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all

**Describe the bug**
Broken link at: https://developer.adobe.com/document-services/docs/overview/pdf-extract-api/howtos/
In the section: For additional information, please refer to [PDF Extract API white paper](https://adobe.sharepoint.com/:w:/s/DCPM/EQUrHgYanq5Iq9PR0XwRIfsBI6uBOu5iG1nRB0t_7amJYA?email=cfrench%40adobe.com&e=JFgscn)

**To Reproduce**
Go to that page and click that link

**Expected behavior**
I would like to read that whitepaper

**Screenshots**
![image](https://user-images.githubusercontent.com/16856016/229940337-8bc24415-8f6d-4365-a53b-311f2f66d111.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cfjedimaster** [comment]
Thank you - reported internally and should be fixed in a future build.

**Comment by AdeelK93** [comment]
thanks @cfjedimaster - I'm quite interested in reading this whitepaper, would it be possible for you to share a link to that, in the event it takes a bit longer to fix in a future build?

**Comment by cfjedimaster** [comment]
https://www.adobe.com/go/pdfextractapi_whitepaper

**Comment by AdeelK93** [comment]
That link still takes me to Adobe's private sharepoint - try that link in incognito, you'll see it's not available to the public

**Comment by cfjedimaster** [comment]
ugh sorry - still waiting to see how this gets fixed

**Comment by cfjedimaster** [comment]
Right link is coming soon, but it's up here now: https://github.com/AdobeDocs/pdfservices-api-documentation/blob/main/src/pages/overview/pdf/Adobe_PDF_Extract_API_Technical_Brief.pdf

**Comment by AdeelK93** [comment]
Thank you!!

**Comment by adityaganotra** [comment]
Hi @AdeelK93 
thanks for pointing this out, this issue has been fixed in the latest deployment.
