### ISSUE TITLE
The url for the python SDK sample repository is not working

### ISSUE THREAD

**Issue by TomeHirata** [AdobeDocs/pdfservices-api-documentation#513]
**Describe the bug**
In the how-to page for Extract PDF API, there is an instruction for the sample repository of Python SDK. But the URL (http://www.adobe.com/go/pdftoolsapi_python_sample) is not working, it leads to the 404 page.

**To Reproduce**
1. Go to https://developer.adobe.com/document-services/docs/overview/pdf-services-api/howtos/extract-pdf/
2. Scroll down to the sample code section and select Python
3. Open the link for the Python sample repository in the comment
4. See the error

**Expected behavior**
The URL leads to https://github.com/adobe/pdfservices-python-sdk-samples 

**Screenshots**
The instruction for the sample repository in the sample code
<img width="790" alt="image" src="https://user-images.githubusercontent.com/33407409/234572559-5b4bd940-c8ba-4748-8fd2-e64c47f11612.png">

The page when I go to the link
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/33407409/234573869-1117ae8c-7430-4bdb-a427-6c0582d74ac6.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Browser: Chrome
 - Version: 112.0.5615.137

**Comment by adityaganotra** [comment]
Hi @TomeHirata , thanks for pointing out the issue.

We have fixed it now.
