### ISSUE TITLE
Word to PDF in Blazor Server Application Fails

### ISSUE THREAD

**Issue by sandyjeakins2** [AdobeDocs/pdfservices-api-documentation#515]
After roughly 20 hours of testing and refactoring I think I have proven that Word To Pdf does not work with Blazor.  I am running .net 7 Blazor server.

I had not tried the Word To Pdf function, but for months I have had the Excel To Pdf conversion running in a production environment with no issues.

Now I need to convert Word documents and it fails.

This call:

FileRef result = createPdfOperation.Execute(exc);

goes out to lunch and never returns.

 

Things I have tried:

1) UnitTested : success

2) Create a bare blazor server app and run this call : fails

3) Create a separate dll to run this call (from the bare test app): fails

4) Execute on new thread: fails

5) Both Static and not Static class calls fail

6) Stream or reading from file makes no difference

My code is attached.
[AdobeFunctions.zip](https://github.com/AdobeDocs/pdfservices-api-documentation/files/11346426/AdobeFunctions.zip)

**Comment by cfjedimaster** [comment]
This repository is not for general support, but only for the documentation. Please share your experience here: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK
