### ISSUE TITLE
Uploading an asset file uploading issue

### ISSUE THREAD

**Issue by sivasurya109** [AdobeDocs/pdfservices-api-documentation#532]
Issue in /src/pages/overview/pdf-extract-api/gettingstarted.md

When i try to upload a file from javascript code it shows the following error.

Access to XMLHttpRequest at 'awsURI' from origin 'www.temp.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

They did not give a option to whitelist my domain. How to upload a file to adobe provided aws URI from client side.

**Comment by cfjedimaster** [comment]
HI, this repository is for documentation source files and stuff, not for support. For support, please use our forums: 

https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all

However, I'll answer this one quickly. The REST APIs are not set up with CORS headers, so you will not be able to use them from client-side JavaScript, nor should you as the credentials would be visible in your source. If you want to build a client-side application that makes use of our APIs, you would set up serverless functions to handle that.
