### ISSUE TITLE
Table of Contents updated Page Numbers after merge?

### ISSUE THREAD

**Issue by stevencwong** [AdobeDocs/pdfservices-api-documentation#642]
Is there any support to update the "Table of Contents" in the Word document with new page numbers after all of the fields have been merged? I cannot find this in the documentation.

Thanks

**Comment by cfjedimaster** [comment]
Hi, this forum is not for general support questions. Please use our forums: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=all&topics=label-documentgenerationapi
