### ISSUE TITLE
Issue in /src/pages/overview/pdf-embed-api/releasenotes.md

### ISSUE THREAD

**Issue by paula-gopo** [AdobeDocs/pdfservices-api-documentation#644]
When listening to ANNOTATION_COUNT event on  PDF Embed API, the event is generated wrong
### Expected Behaviour
event: {type: 'ANNOTATION_COUNT', data: number of annotations}
### Actual Behaviour
event: {type: 'ANNOTATION_COUNT', data: {mentions: undefined}
### Reproduce Scenario (including but not limited to)
Just listen to the event on an embedded PDF:

```
const eventOptions = {
  // Pass the events to receive.
  // If no event is passed in listenOn, then all the annotation events will be received.
  listenOn: [
      "ANNOTATION_COUNT"
  ]
}

previewFilePromise.then(adobeViewer => {
  adobeViewer.getAnnotationManager().then(annotationManager => {
      annotationManager.registerEventListener(
          function(event) { console.log(event.type, event.data) },
          eventOptions
      );
   });
});
```

**Comment by cfjedimaster** [comment]
Hi, this repo is for documentation only. For support, please post here: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions

Note that Adobe is shut down for the week of July 4th.
