### ISSUE TITLE
Adobe bad kerning issue happening 

### ISSUE THREAD

**Issue by SalweiVH** [AdobeDocs/pdfservices-api-documentation#662]
Hi, I am Jared Salwei With Precision for Medicine are business unit is Precision Extract.  I am opening this ticket for two reasons. 

1. We are a paying customer for Adobe and we use it in are product to generate PDFs from word. We have had several people leave the company and I only have access to are adobe api account. I am wondering can you put me in touch with are SalesRep or account owner so we can chat and get the details we are missing? 

2. This is a new issue we have we developed these templates a while ago 2-4 months ago and did not face the issue no extra space. We are wondering if maybe a Api update caused this as we see it now in multiple templates that did not previously have this issue and it's happening on multiple fonts.

### Expected Behaviour
No spaces in the word for example "lilly"

### Actual Behaviour

What it is now "L illy"

#### Logs taken while reproducing [problem]

**Comment by SalweiVH** [comment]
I can provide the Word and PDF files and pictures of the issue if you can tell me how to attach them on this? I don't see an option.

**Comment by cfjedimaster** [comment]
Hi, this forum is not for general tech support. It is only a repo for our documentation. Please visit our support forum here: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions&topics=label-documentgenerationapi
