### ISSUE TITLE
PDF Services API - S3 Transfer Acceleration URL is incorrect

### ISSUE THREAD

**Issue by tYoshiyuki** [AdobeDocs/pdfservices-api-documentation#738]
thank you always.

Issue in /src/pages/overview/pdf-services-api/gettingstarted.md

S3 Transfer Acceleration URL is incorrect.

**Incorrect:**
dcplatformstorageservice-us-east-1-**prod**.s3-accelerate.amazonaws.com

**Correct:**
dcplatformstorageservice-**prod**-us-east-1.s3-accelerate.amazonaws.com

I have attached an image of the results of the survey using Fiddler.

![2023-11-08_231107](https://github.com/AdobeDocs/pdfservices-api-documentation/assets/25566072/988285f3-024d-4e3f-a7df-70b512a90e0e)

**Comment by cfjedimaster** [comment]
If you are talking about the URL used to create new assets - it is NOT one URL - and it is not guaranteed to even be S3. The URL will change so I don't believe this makes sense. Re-open if I misread you though!

**Comment by tYoshiyuki** [comment]
Thank you for your reply.

I am using Adobe PDF Services SDK (.NET).
The document describes the whitelist when using the SDK, and the URL listed there was incorrect, so we filed an issue.

![image](https://github.com/AdobeDocs/pdfservices-api-documentation/assets/25566072/a8c8577f-e070-452a-8f74-3e0e9762a470)

**Comment by cfjedimaster** [comment]
Ahah, that _does_ make sense and is absolutely a documentation bug.

**Comment by tYoshiyuki** [comment]
@jasnoors @cfjedimaster 
Thank you for your response to the correction! 😄
