### ISSUE TITLE
Creating pdf from a tif file is failing with "The input file appears to be corrupted and cannot be processed"

### ISSUE THREAD

**Issue by HarshaShaha** [AdobeDocs/pdfservices-api-documentation#756]
### Expected Behaviour
Creating pdf from jpeg and png is successful and hence it should be successful for tif as well. 
### Actual Behaviour
Its failing with error "The input file appears to be corrupted and cannot be processed"
### Reproduce Scenario (including but not limited to)
    const executionContext = PDFServicesSdk.ExecutionContext.create(credentials),
    CreatePDF = PDFServicesSdk.CreatePDF,    
    createPdfOperation = CreatePDF.Operation.createNew(),
    // Set operation input from a source file.
    input = PDFServicesSdk.FileRef.createFromLocalFile("C:\\Users\\harsh\\Downloads\\adobe\\adobe-dc-pdf-services-sdk-node\\resources\\AUA Form-03272018-21902-1.tif", CreatePDF.SupportedSourceFormat.tif);
    createPdfOperation.setInput(input);

#### Steps to Reproduce
As above

#### Platform and Version
Windows. node.js
#### Sample Code that illustrates the problem
Mentioned above
#### Logs taken while reproducing problem
node .\create-pdf-from-docx.js
Debugger attached.
No logging configuration. Using default config
2023-12-14T17:02:25.014:[INFO]: All validations successfully done. Beginning PDF conversion
Exception encountered while executing operation ServiceApiError: The input file appears to be corrupted and cannot be processed.; requestId=868b1f70-20d3-4068-a70e-75f03de9617a
    at C:\Users\harsh\Downloads\adobe\adobe-dc-pdf-services-sdk-node\node_modules\@adobe\pdfservices-node-sdk\src\internal\api\platform-api.js:200:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  requestTrackingId: '868b1f70-20d3-4068-a70e-75f03de9617a',
  statusCode: 400,
  errorCode: 'CORRUPT_DOCUMENT'
}

**Comment by cfjedimaster** [comment]
This repo is for the documentation and not support issues. Please post to our forums: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?filter=all&sort=latest_replies&tabid=discussions
