### ISSUE TITLE
Issue in Extract Images from PDF service - Service not extracting all images

### ISSUE THREAD

**Issue by RitivikaP** [AdobeDocs/pdfservices-api-documentation#765]
[Doc1.pdf](https://github.com/AdobeDocs/pdfservices-api-documentation/files/13871808/Doc1.pdf)

**Comment by cfjedimaster** [comment]
Issues here are only for doc problems. For technical support, please use our forums: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions
