### ISSUE TITLE
Issue in Adobe PDF Service for large pdfs - Extract Images from PDF throwing error

### ISSUE THREAD

**Issue by RitivikaP** [AdobeDocs/pdfservices-api-documentation#767]
### Actual Behaviour : Error is being thrown from API "Extract Images from PDF" - 
502 : Bad Gateway
Error : Unable to Extract Content- Internal Error

**Comment by cfjedimaster** [comment]
Issues here are only for doc problems. For technical support, please use our forums: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions
