### ISSUE TITLE
Awful

### ISSUE THREAD

**Issue by ASC** [AdobeDocs/pdfservices-api-documentation#807]
Needlessly overcomplicated, totally user-un-friendly API. Cannot even upload an asset. Do not use.

**Comment by cfjedimaster** [comment]
Hi, this repo is for the docs, not technical support, please post your issues here, https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions, although honestly this kind of comment is pretty useless. You say you can't upload an asset - when and if  you post to the support forums, maybe share what you did and what went wrong. I assume you are using the REST API, which is pretty simple imo, but if you tried and failed, share what code you used. I've also got code samples you can use if it helps.
