### ISSUE TITLE
Issue in /src/pages/overview/pdf-extract-api/gettingstarted.md

### ISSUE THREAD

**Issue by angelmnkre** [AdobeDocs/pdfservices-api-documentation#810]
### Expected Behaviour
To receive the location header
### Actual Behaviour
The location header is missing
#### Steps to Reproduce
Step two
curl --location -g --request PUT 'https://dcplatformstorageservice-prod-us-east-1.s3-accelerate.amazonaws.com/b37fd583-1ab6-4f49-99ef-d716180b5de4?X-Amz-Security-Token={{Placeholder for X-Amz-Security-Token}}&X-Amz-Algorithm={{Placeholder for X-Amz-Algorithm}}&X-Amz-Date={{Placeholder for X-Amz-Date}}&X-Amz-SignedHeaders={{Placeholder for X-Amz-SignedHeaders}}&X-Amz-Expires={{Placeholder for X-Amz-Expires}}&X-Amz-Credential={{Placeholder for X-Amz-Credential}}&X-Amz-Signature={{Placeholder for X-Amz-Signature}}' \

--header 'Content-Type: application/pdf' \

--data-binary '@{{Placeholder for file path}}'
#### Platform and Version
Laravel 9
#### Sample Code that illustrates the problem
Even if I put the file path the result is the same
            $htmlContent = file_get_contents($filePath);
            $response = $client->put($endpoint, [
                'headers' => [
                    'Content-Type' => 'application/pdf',
                ],
                'body' => $htmlContent,
            ]);
#### Logs taken while reproducing problem
The response code is 200

**Comment by cfjedimaster** [comment]
Hi, this repo is not for technical support, please post your issue here: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&filter=all&lang=all&tabid=discussions

**Comment by angelmnkre** [comment]
Sorry and thank you for the replay
