### ISSUE TITLE
This application domain (...) is not authorized to use the provided PDF Embed API Client ID.

### ISSUE THREAD

**Issue by roamingphantom** [AdobeDocs/pdfservices-api-documentation#825]
I'm using PDF Embed API in Filemaker application through its webViewer object.
It's working in Filemaker Pro (a desktop version of the solution) but through web direct(web-based of the same solution) it's not working.
I have provided the correct key based on the domain name but it seems Embed API still consider it as not authorized
![image](https://github.com/AdobeDocs/pdfservices-api-documentation/assets/71005671/776d3cfc-64ed-4f8d-b901-c5010d57beb5)

When I try to get the hostname from this webViewer object, it doesn't return anything but adobe still return error message with the correct domain name.

**Comment by roamingphantom** [comment]
Hi, is there any update regarding this?

**Comment by cfjedimaster** [comment]
This repo is not for support, please post your question here: https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all
