### ISSUE TITLE
Issue in /src/pages/overview/pdf-embed-api/index.md

### ISSUE THREAD

**Issue by jezzvaliyatt** [AdobeDocs/pdfservices-api-documentation#879]
### Expected Behaviour
When integrating PDF files into websites, there are issues with iOS devices (iPhone/iPad), particularly with the disappearance of the print button.
 
### Actual Behaviour
It functions flawlessly on desktop computers, including Macs. assuming that iOS devices will also exhibit the same behavior

### Reproduce Scenario (including but not limited to)
All iPhone and iPad models will act and function differently from desktop models.

**Comment by cfjedimaster** [comment]
Hi, this is not the place to make support requests, please use our forums instead: https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all

Also, the lack of print on mobile is documented: https://developer.adobe.com/document-services/docs/overview/pdf-embed-api/gettingstarted/#mobile-support
