### ISSUE TITLE
PDFServicesSDK Support

### ISSUE THREAD

**Issue by mmittal-75** [AdobeDocs/pdfservices-api-documentation#892]
We are into oil and Gas domain business and using a desktop application to C++ to create logs and then we need to print those logs in PDF format and for that we are exploring CreatePDFOperation of PDFServices API SDK for creating PDF using the HTML page and having following queries: 

1. Is there a way to set page margins for PDF? Currently it creates the PDF with some default margins and developer is not having any control to change the page margins.
2. We are using PageLayout to set the page height and width and want to set the height of the PDF more than 200 inches. But it always creates the PDF up to 200 inches and create 2 pages instead of 1.
3. Also, can we set other properties thru the API:

-  DPI
-  Fit To Page Width or Height

**Comment by cfjedimaster** [comment]
This repo is just for the docs, not support. Please post your question here: https://community.adobe.com/t5/acrobat-services-api/ct-p/ct-Document-Cloud-SDK?page=1&sort=latest_replies&lang=all&tabid=all
