### ISSUE TITLE
Error while enabling Auto Save in PDF-embed-api

### ISSUE THREAD

**Issue by mouli18** [AdobeDocs/pdfservices-api-documentation#903]
## READ ME FIRST
This repository is for documentation related to Adobe's PDF Services. If you have a support question, please ask it on our forums: https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all

**Describe the bug**
While Enabling auto save feature in pdf embedded api first comment is saving properly and after the first save the auto save not working properly throwing we are unable to post comment

**To Reproduce**
1. Go to PDF sample Enable Ato save
2. Post your comment wait for the pdf for auto save
3. Post another comment after auto save you will get error popup

**Expected behavior**
Auto save must be working properly multiple save need to work properly

**Screenshots**

<img width="959" alt="PDFAutoSaveError" src="https://github.com/AdobeDocs/pdfservices-api-documentation/assets/52033537/f1d9bb3d-23c1-4a2a-a229-917fdce1fa97">
<img width="959" alt="PDFConsoleError" src="https://github.com/AdobeDocs/pdfservices-api-documentation/assets/52033537/1c240285-9a41-48b2-892e-c265444e454a">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version Version 126.0.6478.127 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cfjedimaster** [comment]
Did you actually read the bug template? :) It looks like you ignored it. Please read the READ ME FIRST on top.
