### ISSUE TITLE
The application domain is not authorized to use PDF Embed API only certain devices (My worst nightmare became true)

### ISSUE THREAD

**Issue by markismail7** [AdobeDocs/pdfservices-api-documentation#945]
Hi,
I'm facing an internment issue with the Adobe PDF Embed API on my website. The API, which I've integrated to display PDFs directly on the page, has been functioning well until recently. Now, I'm encountering an error on some devices that says, "The application domain is not authorized to use the PDF Embed API."

You can imagine the frustration this has caused, not just for me, but also for my customers. This is literally my worst nightmare come true. We need Adobe's help to figure out what's going wrong. The issue appears randomly on certain devices, like iPhones—I have two, and while one works fine, the other encounters the problem.

Ideally, if iFrames could  display PDFs on mobile devices without limitations (only the first page ), I wouldn't need the PDF Embed API at all. PDF Embed API is slow, unreliable, and doesn't utilize the full width of the screen on mobile phones, which makes the viewing experience subpar. It would be much better if the API allowed PDFs to be viewed in full width, similar to how mobile browsers handle them. Any suggestion, would be much appreciated. thanks

**Comment by cfjedimaster** [comment]
Hi, this repo is only for documentation and not support. I'm pretty sure I saw your post on our forums so I think you are good there.
