### ISSUE TITLE
Issue in /src/pages/overview/support.md

### ISSUE THREAD

**Issue by ralfnap2** [AdobeDocs/pdfservices-api-documentation#947]
### Expected Behaviour
PDF Extract, csv Export of tables. Valid csv with Strings in ""
### Actual Behaviour
CSV with Strings without "". Text like Abc, def, 123 will produce 3 cells.

**Comment by cfjedimaster** [comment]
This repo is not for support questions/reports. Please post to our forums: https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all
