### ISSUE TITLE
Issue in /src/pages/overview/pdf-embed-api/releasenotes.md

### ISSUE THREAD

**Issue by suprkain** [AdobeDocs/pdfservices-api-documentation#958]
### Expected Behaviour
Ability run on Safari browser on iOS 18

### Actual Behaviour
Getting an error message that says: 
"This application domain *** is not authorized to use the provided PDF Embed API Client ID.

### Reproduce Scenario (including but not limited to)
Run on Safari browser on iOS 18.

#### Steps to Reproduce
Run on Safari browser on iOS 18.

#### Platform and Version
Safari browser on iOS 18.  I'm currently using an iPhone 15 Pro

**Comment by suprkain** [comment]
I will add that I can view the content of the PDF Embed API on various different desktop browser with no problem.  I can also load it on my iPad running iPadOS 17.7

**Comment by cfjedimaster** [comment]
Hi, these issues are not used for customer support. Please use our forums here, https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all, however, this is a known issue. See the sticky post on top.

**Comment by cfjedimaster** [comment]
Hi, these issues are not used for customer support. Please use our forums here, https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all, however, this is a known issue. See the sticky post on top.

**Comment by cfjedimaster** [comment]
Hi, these issues are not used for customer support. Please use our forums here, https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all, however, this is a known issue. See the sticky post on top.

**Comment by cfjedimaster** [comment]
Hi, these issues are not used for customer support. Please use our forums here, https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all, however, this is a known issue. See the sticky post on top.

**Comment by cfjedimaster** [comment]
Hi, these issues are not used for customer support. Please use our forums here, https://community.adobe.com/t5/document-services-apis/bd-p/Document-Cloud-SDK?page=1&sort=latest_replies&filter=all, however, this is a known issue. See the sticky post on top.
